### ISSUE TITLE
Add ATSAMR21B18 SMD component

### ISSUE THREAD

**Issue by ThomArmax** [thisiswhytheinternetexists/AtmelZllBoard#1]
Hi,

I'm a newbie in hardware and I would like to design a small PCB using ATSAMR21B18 with SMD, not pads, is it hard for you to add this new component version in your atmel-zll.lbr ?

Thanks by advance.

**Comment by DJFliX** [comment]
Hi ThomArmax,

I'm not working on this project anymore but by all means, fork it and re-use the component to add a different package to it. If you were to create and MR I'm happy to merge it if that makes any sense :). 

Kinds regards,

Felix

**Comment by ThomArmax** [comment]
Hi @DJFliX,

Thanks for your answer. Ok I understand.
As I am a newbee in hardware design, if I successfully design the footprint, I'll create a PR.
Otherwise, I'll use the existing footprint

Best regards

Thomas
